/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_example_progressbar_CryptoDev */

#ifndef _Included_com_example_progressbar_CryptoDev
#define _Included_com_example_progressbar_CryptoDev
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     com_example_progressbar_CryptoDev
 * Method:    engine_init
 * Signature: ([B[B)I
 */
JNIEXPORT jint JNICALL Java_com_example_progressbar_CryptoDev_engine_1init
  (JNIEnv *, jobject, jbyteArray, jbyteArray);

/*
 * Class:     com_example_progressbar_CryptoDev
 * Method:    en_crypt
 * Signature: (Ljava/io/FileDescriptor;Ljava/io/FileDescriptor;)I
 */
JNIEXPORT jint JNICALL Java_com_example_progressbar_CryptoDev_en_1crypt
  (JNIEnv *, jobject, jstring, jstring);

/*
 * Class:     com_example_progressbar_CryptoDev
 * Method:    de_crypt
 * Signature: (Ljava/io/FileDescriptor;Ljava/io/FileDescriptor;)I
 */
JNIEXPORT jint JNICALL Java_com_example_progressbar_CryptoDev_de_1crypt
  (JNIEnv *, jobject, jstring, jstring);

/*
 * Class:     com_example_progressbar_CryptoDev
 * Method:    engine_close
 * Signature: ()I
 */
JNIEXPORT void JNICALL Java_com_example_progressbar_CryptoDev_engine_1close
  (JNIEnv *, jobject);

#ifdef __cplusplus
}
#endif
#endif
